repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-build
      - id: go-unit-tests

  - repo: local
    hooks:
      - id: loglinter
        name: loglinter
        entry: go run ./cmd/loglinter
        language: system
        types: [go]
        pass_filenames: true
        args:
          - -check-lowercase=true
          - -check-english=true
          - -check-specials=true
          - -check-sensitive=true
          - -sensitive-words=password,token,api_key
