- id: loglinter
  name: loglinter
  description: Checks log messages for style and security rules
  entry: loglinter ./...
  language: golang
  main: ./cmd/loglinter
  types: [go]
  pass_filenames: false
